### ISSUE TITLE
添加黑名单货物后，会导致连续启动APP。

### ISSUE THREAD

**Issue by fengyong2015** [w21180239/JGM-rapid-automator#1]
因为只收集金色货物，将非金色货物加入黑名单后，遇到上述问题。

建议这样修改能避免：
1、修改配置文件，将金色货物放在循环头部检测
2、
```
if target in self.ban_list:
    print(f'遇到黑名单货物{target.value[8:-4]}提前结束，重启游戏...')
    self.d.app_stop("com.tencent.jgm")
    self.d.app_start("com.tencent.jgm")
    time.sleep(10)
    break
```

基于1的前提下，检测到黑名单货物后直接重启游戏，同时停止循环。

**Comment by w21180239** [comment]
> 因为只收集金色货物，将非金色货物加入黑名单后，遇到上述问题。
> 
> 建议这样修改能避免：
> 1、修改配置文件，将金色货物放在循环头部检测
> 2、
> 
> ```
> if target in self.ban_list:
>     print(f'遇到黑名单货物{target.value[8:-4]}提前结束，重启游戏...')
>     self.d.app_stop("com.tencent.jgm")
>     self.d.app_start("com.tencent.jgm")
>     time.sleep(10)
>     break
> ```
> 
> 基于1的前提下，检测到黑名单货物后直接重启游戏，同时停止循环。

感谢你提出的问题，脚本已经升级，请查看最新版本。
